version: '3.7'

services:
  takserver-db:
    build:
      dockerfile: Dockerfile-takserver-db
    container_name: tak-database
    YOUR_HOSTNAME_HERE: tak-database
    init: true
    networks:
      - net
    ports:
      - 5432:5432
    restart: unless-stopped
    tty: true
  takserver-core:
    build:
      dockerfile: Dockerfile-takserver
    container_name: takserver
    YOUR_HOSTNAME_HERE: takserver
    init: true
    networks:
      - net
    ports:
      - 8443:8443
      - 8446:8446
      - 8089:8089
      - 8444:8444
    restart: unless-stopped
    tty: true
    volumes:
      - ./shared:/opt/tak/certs/shared
      - ./plugins:/opt/tak/webcontent/webtak-plugins/plugins/
networks:
  net:
    name: 'takserver'
    ipam:
      driver: default
      config:
        - subnet: 172.16.16.0/24
