version: '3'
services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
    - /etc/radarr/:/config
    - /media/jellyfin-media/Movies/:/movies
    - /media/jellyfin-media/:/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=America/New_York
  image: linuxserver/radarr

 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
    - /etc/sonarr/:/config
    - /media/jellyfin-media/tv/:/tv
    - /media/jellyfin-media/:/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=America/New_York
  image: linuxserver/sonarr


