version: '3'
services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /media/data/radarr/config:/config
      - /media/data/Media/Movies:/movies
      - /media/data/Media/Movies:/downloads/Movies
      - /media/data/Media/TV:/downloads/tvshows
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/radarr
    networks:
      - media_stack

  sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/data/sonarr/config:/config
      - /media/data/Media/TV:/tv
      - /media/data/qbtorrent/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/sonarr
    networks:
      - media_stack

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/data/jellyfin/config:/config
      - /media/data/Media/TV:/data/tvshows
      - /media/data/Media/Movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /media/data/qbtorrent/config:/config
      - /media/data/Media/Movies:/downloads/movies
      - /media/data/Media/TV:/downloads/tvshows
#     - /media/data/qbtorrent/downloads:/downloads old config 
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - media_stack

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /media/data/jackett/config:/config
      - /media/data/jackett/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9117:9117
    restart: unless-stopped

networks:
  media_stack:
