services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "7878:7878"
      - "8989:8989"
      - "5055:5055"
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
      - "8181:8181"
      - "6882:6881"
      - "6882:6881/udp"
      - "9117:9117"
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    networks:
      example_net:
        ipv4_address: 172.19.0.7

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JACKETT_PORT=9117
    volumes:
      - /path/to/jackett/config:/config
      - /path/to/jackett/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    network_mode: service:gluetun

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - RADARR_PORT=7878
    volumes:
      - /path/to/radarr/config:/config
      - /path/to/Media/Movies:/movies
      - /path/to/Media/Movies:/downloads/Movies
      - /path/to/Media/TV:/downloads/tvshows

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SONARR_PORT=8989
    volumes:
      - /path/to/sonarr/config:/config
      - /path/to/Media/TV:/tv
      - /path/to/qbtorrent/downloads:/downloads

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055
    volumes:
      - /path/to/jellyseerr/config:/app/config

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /path/to/jellyfin/config:/config
      - /path/to/Media/TV:/data/tvshows
      - /path/to/Media/Movies:/data/movies
    restart: unless-stopped
    networks:
      example_net:

  qbittorrentmov:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrentmov
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - WEBUI_PASSWORD=${WEBUI_PASSWORD}
      - WEBUI_USERNAME=${WEBUI_USERNAME}
    volumes:
      - /path/to/qbtorrent/config/mov:/config
      - /path/to/Media/Movies:/downloads/movies

  qbittorrenttv:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrenttv
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8181
      - WEBUI_PASSWORD=${WEBUI_PASSWORD}
      - WEBUI_USERNAME=${WEBUI_USERNAME}
    volumes:
      - /path/to/qbtorrent/config/tv:/config
      - /path/to/Media/TV:/downloads/tvshows

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  example_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
